mysite/urls.py
# mysite/urls.py
from django.conf import settings
from django.conf.urls import url,include
from django.conf.urls.static import static
from django.contrib import admin
from study import views as study_views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^', include('study.urls', namespace='study')),
    url(r'^accounts/signup/$', study_views.signup, name='signup'),
	url(r'^summernote/', include('django_summernote.urls')),
]

if settings.DEBUG: # setting.py의 DEBUG = True인 경우
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

study/urls.py
# study/urls.py

from django.conf.urls import url
from . import views


urlpatterns = [
	url(r'^$', views.postLV.as_view(), name='post_list'),
    url(r'^post/(?P<pk>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^post/new/$', views.post_new, name='post_new'),
    url(r'^post/(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit'),
    url(r'^post/(?P<pk>\d+)/remove/$', views.post_remove, name='post_remove'),
    url(r'^comment/(?P<pk>\d+)/remove/$', views.comment_remove, name='comment_remove'),
    url(r'^comment/(?P<pk>\d+)/edit/$', views.comment_edit, name='comment_edit'),
]

study/models.py
# study/models.py
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from django_summernote import models as summer_model
from django_summernote import fields as summer_fields


class Post(summer_model.Attachment):
	author = models.ForeignKey(settings.AUTH_USER_MODEL)
	title = models.CharField(max_length=200)
	content = summer_fields.SummernoteTextField(default='')
	created_at = models.DateTimeField(auto_now_add=True, null=True)

	class Meta:
		ordering = ['-created_at']

	def get_absolute_url(self):
		return reverse('study:post_detail', args=[self.id])

	def __str__(self):
		return self.title


def user_path(instance, filename):
    from random import choice
    import string
    arr = [choice(string.ascii_letters) for _ in range(8)]
    pid = ''.join(arr)
    extension = filename.split('.')[-1]
    return '{}/{}.{}'.format(instance.author.username, pid, extension)


class Comment(models.Model):
    post = models.ForeignKey('study.Post', related_name='comments')
    author = models.ForeignKey('auth.User')
    text = models.TextField(verbose_name='')
    created_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_date']

    def __str__(self):
        return self.text

study/forms.py
# study/forms.py
from django import forms
from .models import Post, Comment
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class PostForm(forms.ModelForm):
	class Meta:
		model = Post
		fields = ['title', 'content']
		widgets = {
			'title' : forms.TextInput(attrs={'class': 'form-control'}),
		}

    # class Meta:
    #     model = Post
    #     fields = ('title','cover_img', 'origin','video_url', 'video_url2', 'text', 'image')
    #     widgets = {
    #         'title' : forms.TextInput(attrs={'class': 'form-control'}),
    #         'origin' : forms.TextInput(attrs={'class': 'form-control','placeholder': '자료 출처를 입력해주세요.(not required)'}),
    #         'video_url' : forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'YouTube 영상이 있다면 공유 URL을 입력해주세요.(not required)'}),
    #         'video_url2' : forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'YouTube 영상이 있다면 공유 URL을 입력해주세요.(not required)'}),
    #         'text' : forms.Textarea(attrs={'class': 'form-control', 'rows':15}),
    #         # 'image' : forms.FileInput(attrs={'placeholder': '자료 출처를 입력해주세요.(not required)'}),
    #     }


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('text',)
        widgets = {
            'text' : forms.Textarea(attrs={'class': 'form-control', 'rows': 3, 'placeholder': '댓글을 입력해주세요.'}),
        }


class CreateUserForm(UserCreationForm):
    email = forms.EmailField(
        required=True,
        label="이메일",
        widget = forms.TextInput(attrs={'class': 'form-control', 'placeholder': '이메일 주소를 입력해주세요'}),
        )
    username = forms.CharField(
        required=True,
        label="ID",
        widget = forms.TextInput(attrs={'class': 'form-control', 'help_text': ''}),
        )

    password1 = forms.CharField(
        required=True,
        label="비밀번호",
        widget = forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': '숫자와 문자를 포함해 8자리 이상을 입력해주세요'}),
        )

    password2 = forms.CharField(
        required=True,
        label="비밀번호 확인",
        widget = forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': '같은 비밀번호를 다시 입력해주세요.'}),
        )

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
        widgets = {
            'username' : forms.TextInput(attrs={'class': 'form-control', 'help_text': ''}),
        }

study/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.views.generic import ListView
from .models import Post, Comment
from .forms import PostForm, CommentForm, CreateUserForm


def signup(request):
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username = username, password = raw_password)
            login(request, user)
            return redirect('study:post_list')
    else:
        form = CreateUserForm()
    return render(request, 'registration/signup.html', {'form' : form})


class postLV(ListView):
	model = Post
	template_name = 'bsr/post_list.html'
	paginate_by = 7

	def get_queryset(self):
		qs = Post.objects.all()
		q = self.request.GET.get('q', '') # GET request의 get 인자중에 q 가 있으면 가져오고, 없으면 빈 문자열

		if q:
			qs = qs.filter(title__icontains=q)

		return qs


def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        if request.user.is_anonymous():
            return redirect('login')
        form = CommentForm(request.POST)

        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.post = post
            comment.save()
        return redirect('study:post_detail', pk=post.pk)
    else:
        form = CommentForm()
        return render(request, 'bsr/post_detail.html', {'post':post, 'form':form})

@login_required
def post_new(request):
	if request.method == "POST":
		form = PostForm(request.POST, request.FILES)
		if form.is_valid():
			post = form.save(commit=False)
			post.author = request.user
			post.save()
			return redirect(post)
	else:
		form = PostForm()
	return render(request, 'bsr/post_new.html', {'form': form})


@login_required
def post_edit(request, pk):
	post = get_object_or_404(Post, pk=pk)
	if request.method == 'POST':
		form = PostForm(request.POST, request.FILES, instance=post)
		if form.is_valid():
			post = form.save()
			return redirect(post)

	else:
		if post.author == request.user:
			form = PostForm(instance=post)
			return render(request, 'bsr/post_edit.html', {'form':form})
		else:
			return render(request, 'bsr/warning.html')


@login_required
def post_remove(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if post.author == request.user:
        post.delete()
        return redirect('study:post_list')
    else:
        return render(request, 'bsr/warning.html')


@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    if comment.author == request.user:
        post_pk = comment.post.pk
        comment.delete()
        return redirect('study:post_detail', pk=post_pk)
    else:
        return render(request, 'bsr/warning.html')

@login_required
def comment_edit(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post = get_object_or_404(Post, pk=comment.post.id)

    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.created_date = timezone.now()
            comment.save()
        return redirect('study:post_detail', pk=post.pk)

    else:
        form_edit = CommentForm(instance=comment)
        return render(request, 'bsr/post_detail.html', {'post':post, 'form_edit':form_edit, 'pk':comment.pk})

study/templates/bsr/about.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Clean Blog - About</title>

    <!-- Bootstrap Core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Theme CSS -->
    <link href="css/clean-blog.min.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" href="index.html">Start Bootstrap</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="index.html">Home</a>
                    </li>
                    <li>
                        <a href="about.html">About</a>
                    </li>
                    <li>
                        <a href="post.html">Sample Post</a>
                    </li>
                    <li>
                        <a href="contact.html">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-image: url('img/about-bg.jpg')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="page-heading">
                        <h1>About Me</h1>
                        <hr class="small">
                        <span class="subheading">This is what I do.</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostrum molestiae debitis nobis, quod sapiente qui voluptatum, placeat magni repudiandae accusantium fugit quas labore non rerum possimus, corrupti enim modi! Et.</p>
            </div>
        </div>
    </div>

    <hr>

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; Your Website 2016</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="vendor/jquery/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="vendor/bootstrap/js/bootstrap.min.js"></script>

    <!-- Contact Form JavaScript -->
    <script src="js/jqBootstrapValidation.js"></script>
    <script src="js/contact_me.js"></script>

    <!-- Theme JavaScript -->
    <script src="js/clean-blog.min.js"></script>

</body>

</html>

study/templates/bsr/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>몽키와선샤인</title>
    <link rel="icon" href="{% static 'bsr/img/profile-pic.png' %}">

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'bsr/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Theme CSS -->
    <link href="{% static 'bsr/css/clean-blog.css' %}" rel="stylesheet">
	<link href="{% static 'study/style.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
	<link href='//spoqa.github.io/spoqa-han-sans/css/SpoqaHanSans-kr.css' rel='stylesheet' type='text/css'>
    <link href="{% static 'bsr/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<body>

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" href="{% url 'study:post_list' %}">몽키와 선샤인의 영어공부</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{% url 'study:post_list' %}">Home</a>
                    </li>
                    <li>
                        <a href="{% url 'study:post_new' %}">New Post</a>
                    </li>
                    <li>
                        {% if user.is_active %}
                        <a href="{% url 'logout' %}">Logout</a>
                        {% else %}
                        <a href="{% url 'login' %}">Login</a>
                        {% endif %}
                    </li>
                    {% if user.is_authenticated %}
                        <li>
                            <a href="{% url 'study:post_list' %}">welcome, <span class='username'>{{ user.username }}</span></a>
                        </li>
                    {% endif %}
                    <!-- <li>
                        <a href="contact.html">Contact</a>
                    </li> -->
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->


  {% block heading %}
  {% endblock %}


    <!-- Main Content -->
    <div class="container">
        <div class="row">

              {% block content %}
              {% endblock %}
			
        </div>
    </div>

    <hr>

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">

                    <a class="footer" href="https://github.com/wayhome25"><img src="{% static 'bsr/img/profile-pic.png' %}" alt="로고" class="logo">
                    <p class="copyright text-muted">Copyright &copy; 초보몽키 2017</p></a>

            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="{% static 'bsr/vendor/jquery/jquery.min.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'bsr/vendor/bootstrap/js/bootstrap.min.js' %}"></script>

    <!-- Contact Form JavaScript -->
    <script src="{% static 'bsr/js/jqBootstrapValidation.js' %}"></script>
    <script src="{% static 'bsr/js/contact_me.js' %}"></script>

    <!-- Theme JavaScript -->
    <script src="{% static 'bsr/js/clean-blog.min.js' %}"></script>

</body>

</html>

study/templates/bsr/post_detail.html
{% extends 'bsr/base.html' %}
{% load staticfiles %}

{% load staticfiles %}


{% block heading %}
{% if post.cover_img %}
<header class="intro-header" style="background-image: url('{{post.cover_img.url}}')">
{% else %}
<header class="intro-header" style="background-image: url('{% static 'bsr/img/home-bg.jpg' %}')">
{% endif %}
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
              <div class="post-heading">
                <a class="heading" href="/">
                  <h1>{{post.title}}</h1>
                </a>
                  <span class="meta">by <a href="#">{{post.author}}</a>&nbsp;&nbsp;|&nbsp;&nbsp;{{ post.created_at | date:"Y-m-d D" }}</span>
              </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}

{% block content %}

	{% autoescape off %}
	{{post.content|linebreaksbr }}
	{% endautoescape %}


  <div class="post-set-btn">
	<div class="btn-wrap">
  	{% if post.author == user %}
    <a href="{%url 'study:post_edit' pk=post.pk %}">
      <button type="button" class="btn btn-success">수정</button>
    </a>
    <a href="{%url 'study:post_remove' pk=post.pk %}">
      <button type="button" class="btn btn-danger">삭제</button>
    </a>
    {% endif %}
    <a href="{% url 'study:post_list' %}">
      <button type="button" class="btn btn-info">뒤로</button>
    </a>
	</div>

    <hr>

    <form class="" action="" method="post">
      {% csrf_token %}
      {{ form }}
        {% if form_edit %}
        {% else %}
          {% if user.is_anonymous %}
          <span class="comment-login-required"> 댓글 입력을 위해서는 <a href="{%url 'login' %}" class="login-link">로그인</a>이 필요합니다. </span>
          {% endif %}
        <button class="btn btn-default btn-xs comment-save" type="submit">저장</button>
        {% endif %}
    </form>

    {% for comment in post.comments.all %}
      {% if comment.id == pk %}
      <div class="comment">
        <form class="" action="" method="post">
          {% csrf_token %}
          <div class="comment-info">
              <strong>{{ comment.author }}</strong>
              <small>{{ comment.created_date | date:'Y-m-d H:i' }}</small>
              <button class="comment_save" type="submit"><img src="{% static 'bsr/img/edit.png' %}" class="comment_edit" alt="comment_edit_save"></button>
          </div>
            {{ form_edit }}
          </form>
      </div>
      <hr>
      {% else %}
      <div class="comment">
          <div class="comment-info">
              <strong>{{ comment.author }}</strong>
              <small>{{ comment.created_date | date:'Y-m-d H:i' }}</small>
              {% if comment.author == user %}
              <a href="{% url 'study:comment_edit' pk=comment.pk %}"><img class="comment_edit" src="{% static 'bsr/img/edit.png' %}" alt=""></a>
              <a href="{% url 'study:comment_remove' pk=comment.pk %}"><img  class="comment_remove" src="{% static 'bsr/img/delete.png' %}" alt=""></a>
              {% endif %}
          </div>
          {% autoescape off %}
          <p>{{ comment.text|linebreaks}}</p>
          {% endautoescape %}
      </div>
      <hr>
      {% endif %}
    {% endfor %}
  </div>



{% endblock %}

study/templates/bsr/post_edit.html
{% extends 'bsr/base.html' %}
{% load staticfiles %}

{% block heading %}
<header class="intro-header" style="background-image: url('{% static 'bsr/img/home-bg.jpg' %}')">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
              <div class="site-heading">
                <a class="heading" href="/">
                  <h1>Weekly English</h1>
                  <hr class="small">
                  <span class="subheading">Edit Post</span>
                </a>
              </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}


{% block content %}
<div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
	<form method="POST" class="login-form" enctype="multipart/form-data">
		{% csrf_token %}
		<input type="hidden" name="next" value="">
		{{ form.as_p }}
		<input type="submit" class="save btn btn-success" value="수정">
		<a href="{% url 'study:post_list' %}">
		  <button type="button" class="btn btn-danger">취소</button>
		</a>
	</form>
</div>
{% endblock content %}

study/templates/bsr/post_list.html
{% extends 'bsr/base.html' %}
{% load staticfiles %}


{% block heading %}
<header class="intro-header" style="background-image: url('{% static 'bsr/img/home-bg.jpg' %}')">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
              <div class="site-heading">
                  <h1 class><a class="heading" href="/">Weekly English</a></h1>
                  <hr class="small">
                  <span class="subheading">몽키와 썬샤인의 영어공부</span>
              </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}

{% block content %}

<div id="board" class="container">
	<div class="table-responsive text-center">
		<p>
			<form action="" method="get" class="text-right search">
				<input type="text" name="q" value="{{ q }}" placeholder="제목 검색" class="search-input">
				<input type="submit" value="검색" class="btn btn-success search-btn">
			</form>
		</p>
		<table class="table text-center table-hover">
			<thead>
				<tr>
					<th>id</th>
					<th>Title</th>
					<th>Author</th>
					<th>Date</th>
				</tr>
			</thead>
			<tbody>
				{% for post in object_list %}
				<tr>
					<td>{{ post.id }}</td>
					<td><a href="{% url 'study:post_detail' pk=post.pk %}">{{ post.title }} <span class="count">[{{ post.comments.count }}]</span></a></td>
					<td>{{ post.author }}</td>
					<td>{{ post.created_at | date:"Y-m-d D" }}</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
</div>

{% if is_paginated %}

<div class="text-center pagination-wrap">
	<ul class="pagination">
	  {% if page_obj.has_previous %}
	    <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
	  {% else %}
	    <li class="disabled"><span>&laquo;</span></li>
	  {% endif %}
	  {% for i in paginator.page_range %}
	    {% if page_obj.number == i %}
	      <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
	    {% else %}
	      <li><a href="?page={{ i }}">{{ i }}</a></li>
	    {% endif %}
	  {% endfor %}
	  {% if page_obj.has_next %}
	    <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
	  {% else %}
	    <li class="disabled"><span>&raquo;</span></li>
	  {% endif %}
	</ul>
</div>

{% endif %}
{% endblock content %}

study/templates/bsr/post_new.html
{% extends 'bsr/base.html' %}
{% load staticfiles %}

{% block heading %}
<header class="intro-header" style="background-image: url('{% static 'bsr/img/home-bg.jpg' %}')">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
              <div class="site-heading">
                <a class="heading" href="/">
                  <h1>Weekly English</h1>
                  <hr class="small">
                  <span class="subheading">New Post</span>
                </a>
              </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}

{% block content %}
<div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
	<form method="POST" class="login-form col-md-12" enctype="multipart/form-data">
		{% csrf_token %}
		<input type="hidden" name="next" value="">
		{{ form.as_p }}
		<button type="submit" class="save btn btn-success" value="save">save</button>
		<a href="{% url 'study:post_list' %}">
		  <button type="button" class="btn btn-danger">cancel</button>
		</a>
	</form>
</div>
{% endblock content %}

study/templates/bsr/warning.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>

  <script type="text/javascript">
    window.onload = function(){
      alert('잘못된 접근 입니다.')
      window.location.href = "/"
    }
  </script>
  </body>
</html>